### ISSUE TITLE
Can't import .tws file

### ISSUE THREAD

**Issue by faustice** [daterre/Cradle#10]
I am trying to import my twine file, but it wont accept it, and it wont import it as a C# file either. Where am I supposed to put it? Sorry, I am not very good with unity/twine, and I just can't get this thing to work.

**Comment by daterre** [comment]
Hi, sorry about the trouble, here are a few things:
1. Your story must be written for the SugarCube/SugarCane themes - Twine 2 defaults to Harlowe which is not supported.
2. If you have errors in the Unity console window, please delete the generated .cs and made sure that there aren't any errors from your own scripts. The import won't work if you have errors.
3. If you still have trouble, please send your .twee file and I will help you debug.

**Comment by faustice** [comment]
Hi, thanks for the quick reply!
That makes much more sense now, since I was using Harlowe. It wont work with Twine1 .tws files? Because I had tried that as well, to see if it was my Harlowe, and it wouldn't accept that. So are .twee files different from .tws files? 
It's probably just because I wasn't using SubarCube/Cane. Thanks!

**Comment by daterre** [comment]
.tws isn't really a file that can be used outside of Twine 1,  .twee is the
format for exporting. You can export as twee from the file menu in Twine 1.
Hope that helps!

On Monday, January 25, 2016, faustice <notifications@github.com> wrote:

> Hi, thanks for the quick reply!
> That makes much more sense now, since I was using Harlowe. It wont work
> with Twine1 .tws files? Because I had tried that as well, to see if it was
> my Harlowe, and it wouldn't accept that. So are .twee files different from
> .tws files?
> It's probably just because I wasn't using SubarCube/Cane. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daterre/UnityTwine/issues/10#issuecomment-174656772>.
>


-- 
Doron Assayas Terre
interactive • storytelling • code

web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>
