### ISSUE TITLE
Tags break parsing of passages when exported with Twine 2

### ISSUE THREAD

**Issue by PietroBotnar** [daterre/Cradle#11]
I had issues when exporting a twine story with tags using Twine2 and Entweedle 1.0.2 format.
It seems that when a passage contains a tag, the parsing of the entire passage fails. When I switched to Twine 1 everything works as expected. 
I suspect it's an issue with Entweedle 1.0.2 format.

**Comment by daterre** [comment]
I'll take a look, thanks. The next version of UnityTwine won't require Entweedle though, just a published HTML file so things'll be easier on the exporting front.

**Comment by daterre** [comment]
In v2 (Cradle) Twine 2 stories should be published as HTML files into Unity. Entweedle and the .twee format should no longer be used.
