### ISSUE TITLE
Importing .txt story file not generating C# script 😓

### ISSUE THREAD

**Issue by leffel** [daterre/Cradle#13]
Hey there,

I created a really simple story in Twine2 to test this plugin. I followed the instructions for saving a Twee file using the Entweedle format. 

Here is my story file: [import_test.txt](https://github.com/daterre/UnityTwine/files/226629/import_test.txt)
Here is a screenshot of my project Asset hierarchy: https://monosnap.com/file/ROrbhuA949I0yldku0mDmVlBhhbvcx

In this case, "import_test.txt" is the story I imported. I've tried dragging it over and "Import New Asset..." but neither ever generate a C# script. I've also tried doing this at various levels in the hierarchy, like in the base Assets directory, down to the TwineTextPlayer directory.

What am I doing wrong? 😬

**Comment by daterre** [comment]
Hi, try to name the file .twee not .txt!

On Tuesday, 19 April 2016, Nicole <notifications@github.com> wrote:

> Hey there,
>
> I created a really simple story in Twine2 to test this plugin. I followed
> the instructions for saving a Twee file using the Entweedle format. I've
> attached my story file below.
>
> Here is a screenshot of my project Asset hierarchy:
> https://monosnap.com/file/ROrbhuA949I0yldku0mDmVlBhhbvcx
>
> In this case, "import_test.txt" is the story I imported. I've tried
> dragging it over and "Import New Asset..." but neither ever generate a C#
> script. I've also tried doing this at various levels in the hierarchy, like
> in the base Assets directory, down to the TwineTextPlayer directory.
>
> What am I doing wrong? 😬
>
> import_test.txt
> <https://github.com/daterre/UnityTwine/files/226629/import_test.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/daterre/UnityTwine/issues/13>
>


-- 
Doron Assayas Terre
interactive • storytelling • code

web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>

**Comment by leffel** [comment]
Thanks for the quick response! I did that, but it kept renaming it to `import_test.twee.txt`

I'm using a Mac. Is the Mac OS just trying to be particularly helpful with adding `.txt`?

**Comment by leffel** [comment]
Okay, I found a workaround!

I opened the `import_text.txt` file with MonoDevelop, then used `Save As...` to drop the `.txt` and it generated the C# script. Thank you!!

**Comment by johnbourne** [comment]
Hey Nicole:
That was quite a nice discovery.  I did the same thing on my MAC and wow... a C# file was generated.  So that works.  However, I could not get the TwineTextPlayer to recognize the c# file in the story variable.  What did you do to get that to work?

John

**Comment by daterre** [comment]
Cradle (UnityTwine version 2) now supports stories in HTML format, simply publish your story as save it to your Unity project's Assets folder.
