### ISSUE TITLE
Support for objects and arrays in the Sugar story format

### ISSUE THREAD

**Issue by mlagache** [daterre/Cradle#14]
Hi !
First of all, wonderful work. Cheers!

I'd like to ask if you can help me on having some improvements on data analysis. Or at least pointing out where and how I could add features. I'm working with writers that can't do without some of the expressions or variables in twine. I've already simplified a lot of stuff with them, but there is still two or three things I can't symplify. And I'm not that comfortable with regex and your code. 

Those would be : 

- 1) having default values for variables, writers have this kind of useless passage (for the story, not for the system) where they list all of their variables, and intialize those vars with important values, like : 

`<<set $my_var = "Blablabla">>`

or

`<<set $my_var = false>>`

--> when I compile, there does'nt seem to have default values to the extracted and parsed for variables. This is problematic. I guess it's doable with regex, but I can't find the proper way to do this without introducing a big dirty mess in your code !   :)

- 2) is it possible to have a TwineVar that would behave as an array or a list ? Writers have this kind of easing in the way they setup variables : 

`<<set $myVar = ["value1", "value2", "value3", "value4", "value5"]>>`

they use it, in an "enum" way or something close enough. I managed to add the "array access style" in TwineVar, but I didn't manage to get the values given in twine.

- 3) And more generally speaking, how can you add info to the passages without breaking syntax in Twine ? Something like an id i could use in Unity, but that would be transparent for text content we parse. This is mainly for : 
    - detecting there is a textbox, 
    - having a mapping (with ids for instance) between passages and something like a map in unity game
    - displaying some texts differently, when writers want to have bold; italic, colors or anything...

Thanks a lot !

PS : I don't need full code, but if you could just say if it's possible, explain me how to do it and point out where, that would be awesome.
PS : they use sugarcube, then entweedle, with very basic syntax so that it's compatible with your plugin

**Comment by daterre** [comment]
Hi!

You raise a lot of good questions and I'm happy that it's being put to
serious use. I'll go over some options for you tomorrow in an email but I
just want to mention that a new version that supports the Harlowe format
(including arrays and maps and custom macros) will be ready for beta in a
few days, and the current code in the GitHub repo is already stable if you
want to give it a try (just a few loose ends, default vars is one of them
actually). It supports published html files in addition to twee, so it's a
much better fit for Twine 2.


On Tuesday, 10 May 2016, mlagache <notifications@github.com> wrote:

> Hi !
> First of all, wonderful work. Cheers!
>
> I'd like to ask if you can help me on having some improvements on data
> analysis. Or at least pointing out where and how I could add features. I'm
> working with writers that can't do without some of the expressions or
> variables in twine. I've already simplified a lot of stuff with them, but
> there is still two or three things I can't symplify. And I'm not that
> comfortable with regex and your code.
>
> Those would be :
>
>    - 1) having default values for variables, writers have this kind of
>    useless passage (for the story, not for the system) where they list all of
>    their variables, and intialize those vars with important values, like :
>
> <<set $my_var = "Blablabla">>
>
> or
>
> <<set $my_var = false>>
>
> --> when I compile, there does'nt seem to have default values to the
> extracted and parsed for variables. This is problematic. I guess it's
> doable with regex, but I can't find the proper way to do this without
> introducing a big dirty mess in your code ! :)
>
>    - 2) is it possible to have a TwineVar that would behave as an array
>    or a list ? Writers have this kind of easing in the way they setup
>    variables :
>
> <<set $myVar = ["value1", "value2", "value3", "value4", "value5"]>>
>
> they use it, in an "enum" way or something close enough. I managed to add
> the "array access style" in TwineVar, but I didn't manage to get the values
> given in twine.
>
>    - 3) And more generally speaking, how can you add info to the passages
>    without breaking syntax in Twine ? Something like an id i could use in
>    Unity, but that would be transparent for text content we parse. This is
>    mainly for :
>       - detecting there is a textbox,
>       - having a mapping (with ids for instance) between passages and
>       something like a map in unity game
>       - displaying some texts differently, when writers want to have
>       bold; italic, colors or anything...
>
> Thanks a lot !
>
> PS : I don't need full code, but if you could just say if it's possible,
> explain me how to do it and point out where, that would be awesome.
> PS : they use sugarcube, then entweedle, with very basic syntax so that
> it's compatible with your plugin
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/daterre/UnityTwine/issues/14>
>


-- 
Doron Assayas Terre
interactive • storytelling • code

web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>

**Comment by mlagache** [comment]
Cool !
Maybe there's another way to deal with vars values, but it's important for authors :(

Thx, can't wait to test the new one.

**Comment by daterre** [comment]
Okay here are some more specific answers.

1) Having default values: unfortunately UnityTwine 1.1 doesn't use the the [StoryInit](http://www.motoslave.net/sugarcube/2/docs/special-names.html#special-passages) passage, but you can simulate this pretty simply by doing the following (make sure you uncheck AutoPlay on the story):

    ```c#
    // Assign this in the editor
    public TwineStory story;

    void Start() {
        string realStartPassage = story.StartPassage;
        story.StartPassage = "StoryInit";
        story.Begin();
        story.GoTo(realStartPassage);
    }
    ```

2) Array vars: UnityTwine 2.0 (alpha) includes a significant upgrade to the TwineVar system that can support any type. Arrays and other collections are supported by default for Harlowe. For Sugar formats things are a bit trickier, but hopefully I'll have a solution for that in the upcoming release. In the meantime, if you do use 2.0 you can add basic array support as follows (untested):

  	(a) Create a few helper JavaScript functions in the Twine2 Javascript script editor by going to "Edit Story JavaScript":

    ```js
    window.TwineArray = {
      From: function() {
          return [].slice.call(arguments);
      },
      Get: function(arr, i) {
          return arr[i];
      }
    ```
    
    You can then use it in Twine and it will behave normally in the HTML version.
    
    ```
    <<set $myVar = TwineArray.From("value1", "value2", "value3", "value4", "value5") >>
    <<print TwineArray.Get($myVar, 2)>>
    ```
    
    (b) To make it work the same way in Unity, you'll need to create a class with a similar implementation:
    ```c#
    public static class TwineArray
    {
    	public static TwineVar From(params TwineVar[] values)
        {
        	return new TwineVar(values);
        }
        
        public static TwineVar Get(TwineVar twVar, int index)
        {
        	var array = (TwineVar[]) twVar.InnerValue;
            return array[index];
        }
    }
    ```
   
3) A few things you can do here:

	* A quick & dirty method for adding meaning to text blocks is to designate some variable, say $textbox, and set it to different values as you go along. For an example, check out the way Snoozing and the TwineTextPlayer use $wait and $click.
	* You can add a custom code generating macro that handles `<<textbox "example">>`  and `<</textbox>>` which could translate to C# as `BeginTextbox("example")` and `EndTextbox()` . I can include an example for that if you wish.
	* If you use Harlowe with UnityTwine 2.0, style macros are supported, all you need to do is inspect each TwineOutput's Style property for a key/value list of all applied styles. You can even add your own custom styles very easily. No documentation yet, I'm working on that.
	* Regarding mapping passages to IDs, I recommend simply using the tags of the passage.

**Comment by mlagache** [comment]
Thx a lot, I'll test all of those hints as soon as possible.

When i was talking about default values, it was not exactly that, it's just that when writers put some default values for vars, i don't have them in the compiled .cs.

For instance : 

`<<set $my_var = "Blablabla">>`

is parsed as : 

`public TwineVar my_var ;`

it should be (my guess)

`public TwineVar my_var = "Blablabla";`


I'll keep you updated.
Is the last version of the git hub containing everything you told me about ?

If you say you add features related yto Harlowe, maybe asking writers to use Harlowe would be simpler don't you think ?

Thx a lot dude !

**Comment by daterre** [comment]
Well, a set macro simply sets a variable to a value, it doesn't care whether its value was set before or not. Because in C# all variables must be declared, the importer declares them at the top of the class, but the set macro will still be set in the same place as it is written in Twine. Search for `my_var = "Blablabla"` and you should find it.

Yes the current code in GitHub contains everything, but whether you should use it or not depends on how far a long you are in your project. If you can afford to rewrite everything in Harlowe at this point then you definitely should, but please keep in mind there might be issues while still in alpha. (I of course will help you solve them).

**Comment by mlagache** [comment]
So I guess I did modify something in the parsing stuff :(
Cause I can't find it. All of my vars have nothing set as a value.

I'll have a look. 

Thx again !

**Comment by mlagache** [comment]
Hey !

I can't make Craddle work with my story, both .html (sugarcube) ans .twee (Entweedle) aren't working. 

Got (for the .twee version)

`Story compilation error at passage Panel du personnage: Keyword `void' cannot be used in this context
`

and (for .html) : 

`The story ExampleEntweedle.twee has some errors and can't be imported
ReferenceError: Can't find variable: $

[
    {
        "file": "undefined",
        "line": 11,
        "function": ""
    }
]

Timeout while trying to extract the story data.

StoryImportException: HTML or JavaScript errors encountered in the Harlowe story. Does it load properly in a browser?
`

Do you have an idea ?

**Comment by daterre** [comment]
Please send me your story files and I'll check!

On Tuesday, 17 May 2016, mlagache <notifications@github.com> wrote:

> Hey !
>
> I can't make Craddle work with my story, both .html (sugarcube) ans .twee
> (Entweedle) aren't working.
>
> Got (for the .twee version)
>
> Story compilation error at passage Panel du personnage: Keywordvoid'
> cannot be used in this context
> `
>
> and (for .html) :
>
> `The story ExampleEntweedle.twee has some errors and can't be imported
> ReferenceError: Can't find variable: $
>
> [
> {
> "file": "undefined",
> "line": 11,
> "function": ""
> }
> ]
>
> Timeout while trying to extract the story data.
>
> StoryImportException: HTML or JavaScript errors encountered in the Harlowe
> story. Does it load properly in a browser?
> `
>
> Do you have an idea ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/daterre/Cradle/issues/14#issuecomment-219639783>
>


-- 
web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>

**Comment by mlagache** [comment]
[Example.html.txt](https://github.com/daterre/Cradle/files/267609/Example.html.txt)
[ExampleEntweedle.twee.txt](https://github.com/daterre/Cradle/files/267610/ExampleEntweedle.twee.txt)

**Comment by daterre** [comment]
Thanks, I'll get back to you this evening

**Comment by daterre** [comment]
Okay, I checked your files.

**Example.html** - for some reason, the HTML is missing everything except the bare-bones story data - it doesn't even load in the browser. Not quire sure how you published it... when I imported it to Twine 2 and re-exported, I got the correct format. It then had the same errors as the twee file:

**ExampleEntweedle.twee** - The story compilation errors are because of the use of arrays and object literals. These will not be supported directly for SugarCube in the upcoming version. You do have 2 options though: either use Harlowe, which already supports them, or follow the instructions on arrays and objects in the [Sugar documentation](https://github.com/daterre/Cradle/blob/master/Assets/Cradle/Documentation/Sugar.md).

I did see 2 more issues thought that are definitely bugs:
- Some of the HTML escaped characters weren't unescaped properly
- The .twee importer didn't import Unicode characters correctly

Will fix those bugs tomorrow.

**Comment by mlagache** [comment]
Thx ! Awesome.
I'll have a look at those sugar stuff.
Writers give me an html file they save and load in twine. They never use a browser.

**Comment by daterre** [comment]
Hi,

I went through the code, fixed bugs where applicable and corrected your Twine file. [You can download the results from here](https://www.dropbox.com/s/2op6gqy8fyaq6yg/mlagache.zip?dl=0).

Here's what I did:
* Imported the broken HTML file you sent me (please ask your writers how they exported it!) to Twine 2
* Replaced array and object -related code according to the [Sugar documentation](https://github.com/daterre/Cradle/blob/master/Assets/Cradle/Documentation/Sugar.md)
* Re-published as a valid SugarCube HTML story.

It imported correctly, but broke while playing because there is use of the <<texbox>> macro which is not supported in Cradle (and instead defaults to showing a passage named "textbox", which doesn't exist). However, I made an example to show you how you can add your own version of this macro to Cradle:
1. In a folder called "Editor", I created a script that extends the SugarTranscoder macro list with some code to export.
2. In another script, I extended the imported story script (with the 'partial' keyword') to add a function called ShowTextbox.

You can see these scripts, along with a scene file that plays the story, in the zip linked above.

Regarding the bug with Unicode characters in the twee file, you just need to make sure to save the file with UTF-8 encoding.

**Comment by mlagache** [comment]
Thank you so much ! I won't be able to test it until sunday but I'll keep in touch next week.

Cheers dude !

**Comment by mlagache** [comment]
Awesome ! I didn't ask so much :)
Is what you did with textbox the easy way for unsupported macros ? 

`SugarTranscoder.CodeGenMacros["textbox"] = textbox;` --> get those unsupported macros

All I need is to create a partial extended class with the name of the method I want for unsupported macros ?

`protected void ShowTextbox(string value, string title)` --> add this before compile ?


Concerning the html, I have no idea, I just receive files, never edit them in twine2. But it's actually working inside Twine. I guess they don't publish files but just give me the saved files (dicuments folder I think) which are lighter (no js functions, just pure "tw-passagedata". I can confirm that those files don't work inside a web browser, but works just fine inside twine.

Is this the right way to proceed then ? Always "publishing" before importing inside Unity ?

Thx again !

**Comment by daterre** [comment]
>
> All I need is to create a partial extended class with the name of the
> method I want for unsupported macros ?


Basically there are 2 steps:

   1. In a static editor class, define one ore more code gen macros and
   assign them to the transcoder. A code gen macro is a function that adds
   some code to the generated script. In this case, I assigned to the
   "textbox" macro a function called "textbox" which generates a call to
   ShowTextbox.
   2. In a partial class with the same name I added the definition of
   ShowTextbox. However, you could instead generate in step 1 a call to
   SomeStaticClass.ShowTextbox, and then you could to define ShowTextbox in
   that static class.

Regarding publishing, yes at the moment a published HTML is required, temp
Twine2 files won't work.

Cheers


web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>

**Comment by mlagache** [comment]
Thank you very much, everything's working fine.
Last thing I need to add for writers, is the "click" macro. I know it's not working yet, but

Consider this : 

`<<click "au loin">><<set $loin = true>><</click>>`

I tried your method, I defined a macro "click" and another one "/click".


```
        SugarTranscoder.CodeGenMacros["click"] = click;
        SugarTranscoder.CodeGenMacros["/click"] = ignore;
```

On the macro click, I only receive 
   --> "argument = au loin"
   --> "macro = click"

For /click, I did this just to ignore the closing tag.


Problem is I can't figure how to get what's inside <<click> and <</click>, in this example it's just a variable setting. (<<set $loin = true>>) I guess the difficulty about this is that you get first all the <<set>> macros...

Any clue on how to get this real ?


Thx again, awesome work !

Cheers.

**Comment by daterre** [comment]
To perform an action only upon click, the contents of the macro mustn't be run upon passage enter, but only at a later time. This is called a "passage fragment" in Cradle. Passage fragments are not supported at all by the Sugar format I'm afraid - the only way to use them is by using a regular link with variable setters, or by simply defining the code in a separate passage. However, `click` and `link` macros that use passage fragments are supported in Harlowe, so I recommend checking that out.

**Comment by mlagache** [comment]
Ok. I'll check. But my writers still want that click macro... and don't want to use Harlowe. :(

I managed to add textboxes, get values and set to vars, it works just fine, tahnk you very much.

but I have difficulties to display them properly inside the TwineTextPlayer content : 

Before clicking on an input : 

![textboxes_1](https://cloud.githubusercontent.com/assets/13675677/15633440/fb364c36-25ac-11e6-91f2-f3857e54621c.png)

After clicking : 

![textboxes_2](https://cloud.githubusercontent.com/assets/13675677/15633441/fd35ecc6-25ac-11e6-9065-66c9848d4f13.png)


On click, inputs get small, and I have no clue why...
I've added a "horizontal layout group " to display them inline.

I also did this, but I can't say if it's nice or bad, might be the cause : 

    ```
public void ShowTextBox(string value, string title) {
        Debug.Log(value + " / " + title);

        InputField input = (InputField)Instantiate(InputTemplate);
        
        input.gameObject.SetActive(true);
        input.name = "[[" + title + "]]";
        
        input.onEndEdit.AddListener((string val) =>
        {
            Debug.Log(val);
            Story.Vars[value.Remove(0, 1)] = val;

        });
        

        RectTransform rect = ((RectTransform)input.transform);
        rect.SetParent(Container);
        if(lastAddedIndex >= 0)
            rect.SetSiblingIndex(lastAddedIndex);

        var elem = rect.gameObject.AddComponent<TwineTextPlayerElement>();
        elem.SourceOutput = lastAddedOutput;

    }
```


--> lastAddedIndex & lastAddedOutput are from "DisplayOutput", cause I don't have an "Output" class for input fields, and no available index.

Last thing : for setting values of my vars, I had to remove "$" from the name var. Would you do this too, or is there a way to access vars with those dollars ?


Thanks again !

**Comment by daterre** [comment]
1)
a. Regarding textboxes, I'm not the biggest expert on Unity UI but I think it has something to do with the "preferred" width of the textbox. Try to add a Layout Element component to it, you can fiddle with min/max/preferred sizes there.

b. To get an output object with an index, you could change your code gen macro to yield a custom class that derives from StoryOutput, something like this: `yield return new StoryTextbox()`. Then you will get it in the DisplayOutput function of the text player, where you can add another "else" to pick the right template to show for this textbox. It would be a more "native" way to handle an inline item.

2) Vars use the $ prefix to identify themselves in Twine, but in C# this is not a valid name for a variable so its removed. What you did is fine.

3) To get the tags of the current passage, you can use story.Tags. 

Hope that helps!
