### ISSUE TITLE
Win32Exception on Mac

### ISSUE THREAD

**Issue by proxycase** [daterre/Cradle#18]
I'm getting this funky error when I drag-drop my Harlowe formatted story into Unity. I know it's not my file because I've tried it with the example story files and it gives me the same error (in fact this error is from dragging Clockwork.html into the Assets folder.)

Win32Exception: ApplicationName='/Users/hughsato/PlantDialogue/Assets/Cradle/Editor/ThirdParty/PhantomJS/bin/osx/phantomjs', CommandLine='"phantom.js" "file:///Users/hughsato/PlantDialogue/Assets/Clockwork.html" "/Users/hughsato/PlantDialogue/Assets/Cradle/Editor/.js/StoryFormats/Harlowe/harlowe.bridge.js"', CurrentDirectory='/Users/hughsato/PlantDialogue/Assets/Cradle/Editor/.js'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Cradle.Editor.Utils.PhantomJS.Run[HarloweStoryData] (System.String url, System.String bridgeScriptPath, Boolean throwExOnError) (at /Users/daterre/Projects/UnityTwine/unity/UnityTwine/Assets/Cradle/.src/Cradle.Editor/Editor/Utils/PhantomJS.cs:36)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()

**Comment by proxycase** [comment]
Seems as though I may have been just doing it wrong.

I was adding the entire Cradle repository into Unity.
Fix: Install only the items inside "Assets" to your assets folder. I'm a bit of a Unity noob.

**Comment by daterre** [comment]
Happy you found the issue and closed it! There's no .unitypackage yet so
you need to be familiar with the folder structure to install.

web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>
