### ISSUE TITLE
Location of Mono bin dir changed in Unity 5.4

### ISSUE THREAD

**Issue by mlagache** [daterre/Cradle#23]
Hi. We still have the problem, even if we update the craddle dlls :(

We still have hardcoded paths to /Users/Documents/Daterre/...

We also have tried those solutions : AngryAnt/Behave-release#21

Any hints ?
Thx !

**Comment by daterre** [comment]
Hi, could you please post your Unity console contents?

**Comment by mlagache** [comment]
SystemException: Error running gmcs: Cannot find the specified file
Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames)
Mono.CSharp.CSharpCodeCompiler.CompileFromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources)
Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources)
System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at /Users/daterre/Projects/UnityTwine/unity/UnityTwine/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:161)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)

**Comment by daterre** [comment]
A few questions:
1. What version of Unity are you using? (full version number please)
2. What is your Unity installation directory?
3. Where did you see a hardcoded path to /Users/documents? (the path in the console is just debugging info, it does not affect the actual plugin -- I keep it in for the beta testing phase).

**Comment by daterre** [comment]
Let's continue this in the original issue: https://github.com/daterre/Cradle/issues/21
