### ISSUE TITLE
StoryOutput reference in macro functions

### ISSUE THREAD

**Issue by daterre** [daterre/Cradle#27]
Asked via email:

I want to create a macro similar to <<print $var>> in that it results in the function being replaced with text in that part of the passage, but get a reference to the resulting StoryOutput in C#. Hoping that I can use this kind of thing to make StoryLinks with weird behaviors.

For example, if I make a custom macro <<textOutput param1, param2>>, in C# the function I'd like to implement that with:

```
[RuntimeMacro] 
public void multilink (StoryOutput resultingOutput, string param1, string param2)
{ 
  // resultingOutput is the StoryOutput this macro generates
}
```
 
Is this kind of thing possible with Cradle at the moment?

**Comment by daterre** [comment]
It is indeed possible and it's called a "code generation macro" because you need to generate code for a yield statement. I might add support for something like you suggest - since it's pretty intuitive - but in the meantime, to get it done you can look at [how Snoozing does it](https://github.com/daterre/Cradle/blob/master/Assets/Cradle/Examples/Snoozing/Twine/Editor/SnoozingCodeGenMacros.cs). In short:

1. You write an editor script that assigns a new function to either `SugarTranscoder.CodeGenMacros["nameOfMacro"]` or HarloweTranscoder.CodeGenMacros["nameOfMacro"] (depending on your story format).
2. You either call `transcoder.Code.Buffer.AppendLine("yield return new StoryLink(...);")` or one of the transcoder.Generate* functions which do the work for you (mostly relevant for Harlowe).

You can also look at how the builtin code gen macros are defined: [Harlowe](https://github.com/daterre/Cradle/blob/master/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweCodeGenMacros.cs) and [Sugar](https://github.com/daterre/Cradle/blob/master/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Sugar/SugarCodeGenMacros.cs)

More details can be found [on this issue](https://github.com/daterre/Cradle/issues/14#issuecomment-219993914) (download the linked zip for an example).

I'm keeping this issue open though because I want to try to implement your suggestion.

**Comment by BrodyB** [comment]
Thanks so much for this, dude!!

**Comment by BrodyB** [comment]
I'm not sure I'm understanding how to create a macro in Sugar that uses multiple arguments. When I try to do `<<macro argument1 argument2>>` it seems to show an error when encoding the HTML. Am I doing something wrong, or how should that look?

**Comment by daterre** [comment]
Could you port the error log or a screenshot of the error?

**Comment by daterre** [comment]
Here's how the default Sugar codegen macros handle multiple args - `SugarTranscoder.ParamsWithCommas` is your answer.

```
public static SugarCodeGenMacro DisplayShorthand = (transcoder, macro, argument) =>
{
	string passageExpr = transcoder.BuildExpression(macro);
	string args = argument != null ? transcoder.BuildExpression(argument) : null;
	if (!string.IsNullOrEmpty(args))
		args = ", " + SugarTranscoder.ParamsWithCommas(args);

	transcoder.Code.Indent();
	transcoder.Code.Buffer
		.AppendFormat("yield return passage(\"{0}\"{1});", passageExpr, args)
		.AppendLine();
};
```

**Comment by BrodyB** [comment]
Ah, I think I misinterpreted both the error and the ParamsWithCommas before. I see now that the error I was getting was related to how my code gen macro was putting the newly-formatted arguments into code, and from my misunderstanding of the transcoder methods being used.

![screen shot 2016-11-11 at 10 43 16 am](https://cloud.githubusercontent.com/assets/2968043/20229744/fd2ed96c-a80c-11e6-8bb1-c02b490a708e.png)

```
public static SugarCodeGenMacro MultiLink = (transcoder, macro, argument) =>
	{
		// Takes <<multilink "one" "two">> and turns it into 'multilink, "one", "two"'
		string passageExpr = transcoder.BuildExpression(macro);
		string args = argument != null ? transcoder.BuildExpression(argument) : null;
		if (!string.IsNullOrEmpty(args))
			args = ", " + SugarTranscoder.ParamsWithCommas(args);

		// Inject that into the C# script
		transcoder.Code.Indent();
		transcoder.Code.Buffer
			.AppendFormat("Debug.Log({0}{1});", passageExpr, args) // <- Error 'cause Debug.Log doesn't take multiple arguments. Otherwise fine
			.AppendLine();
	};
```

**Comment by daterre** [comment]
That's the right track. You probably don't need the line `string passageExpr = transcoder.BuildExpression(macro);` because that is used specifically for the shorthand display macro.

**Comment by daterre** [comment]
You can now make any runtime macro return atype derived from StoryOutput. 
```c#
[RuntimeMacro]
public StoryText HelloWorld()
{
    return new StoryText("Hello World!")
}
```

Usage it in your story like this:

Harlowe: `(hello-world:)`
Sugar: `<<helloWorld>>`
