### ISSUE TITLE
Sugar - Custom runtime macros not called by generated story script

### ISSUE THREAD

**Issue by BrodyB** [daterre/Cradle#30]
In Twine, I've created the following blank-slate macro in a script passage titled "setTextDisplay":
`macros['setTextDisplay'] = { handler: function() {} }`

And I implemented it as a runtime macro in Unity:
```
using UnityEngine;

public class CustomRuntimeMacros : Cradle.RuntimeMacros
{
	[Cradle.RuntimeMacro("setTextDisplay")]
	public void SetTextDisplay (string displayName)
	{
		Debug.Log("Macro: SetTextDisplay");
	}
}
```

However, when I implement this in a Twine (Sugarcane, Twine 1.4.2) passage with `<<setTextDisplay "main">>`, the generated C# script places a `passage` command:
```
IStoryThread passage12_Main()
{
	yield return passage("setTextDisplay", "main");
	yield return lineBreak();
	yield break;
}
```

This doesn't seem like the intended functionality to me. I expect this should look to the runtime macro I specified, but that function is never called.

**Comment by daterre** [comment]
I see that Sugar is currently lacking RuntimeMacro support. I'll add it ASAP.

**Comment by daterre** [comment]
I committed an update with this functionality. Unknown Sugar macros still revert to displaying a passage, as expected in the original SugarCane format. Testing appreciated!

**Comment by BrodyB** [comment]
From my initial testing, it looks like it's working exactly as intended now.

In my generated story script, I see:
```
@TwineTestStory()
{
	this.StartPassage = "Start";

	base.Vars = new VarDefs() { Story = this, StrictMode = false };

	macros1 = new UnityTwineTestMacros() { Story = this };
	macros2 = new RoomRuntimeMacros() { Story = this };
}
```
and passages that use the new macros generate properly!
```
IStoryThread passage17_Main()
{
	macros2.SetTextDisplay("secondary");
	yield return lineBreak();
	yield return text(@"""Nantucket sucks!""");
	yield return lineBreak();
	yield return text(@"""I agree!""");
	yield return lineBreak();
	yield return text(@"""Let's never visit Nantucket again.""");
	yield break;
}
```

All is looking good! Thanks so much!
