### ISSUE TITLE
Support HTML tags in Harlowe

### ISSUE THREAD

**Issue by terjegran** [daterre/Cradle#31]
Hiya,

I doing some research and came across this great plugin for Unity.

As I'm testing around with Twine and Cradle I seem to have come across an issue (or it might be I just can't figure out where to get the data from).

When I test my story in Twine it will correctly show me HTML formatting done with simple HTML tags (<b></b> etc), but when the story is imported to Unity using Cradle, the HTML formatting is gone. In the generated .cs file, I can see that the sentence is broken up in the correct spot(s) of the sentence. 

F.ex.
Twine text: 
`Hello <b>world</b>`

Unity:
`yield return text("Hello ");`
`yield return text("world");`

So my question is, is there a way to get the HTML rich tags to work with Cradle? And if so, how?

I'm using Twine 2.0 and Harlowe story format.

**Comment by terjegran** [comment]
So I've been digging around a bit more and it seems like there are ways to get simple HTML formatting using special syntaxes:
* italic; //some text//
* bold: ''some text''
* strikeout: ~~some text~~
etc.
See HarloweTests.html for more examples.

This works okay, but I want to use some custom HTML tags to manipulate text in conjunction with TextMeshPro. And because I use TextMeshPro I would actually prefer to have the HTML tags as part of the text, so I don't have to manipulate the text back to using HTML tags instead of the above-mentioned custom syntax.

After digging through the source code I've found that if I comment out the section where "tag" is ignored in "harlowe.bridge.js_" and and "HarloweTranscoder.cs" add "tag" as one of the switch-cases in the "GenerateBody" function, I get the desired effect.

It would be nice to have a way of enabling this in a setting somewhere? Or is there another simpler way to do this? Some way to tag a section of text to be forced as text and therefore not split up?

Kind regards
 -TJ

**Comment by daterre** [comment]
Hi, 

Sorry for not replying sooner. Adding support for tag sounds like a great idea! I'll add it, or you can create a pull request if you have that set up.

Since I'm using the original Harlowe parser directly, any tokens it recognizes can generally be recognized by Cradle. I'll check if there's some way to recognize a "do not parse" raw string.

Thanks for the ideas!

**Comment by terjegran** [comment]
Hiya,

Thanks for the reply.

I do have a version that let HTML tags get processed, and I have tried today to add a pull request. The problem is that for some reason (I don't know why), I get a "The requested URL returned error: 403". So I have not been able to do it. Does this mean I don't have access to write to the repo?

The changes I have made are really simple so I'll describe them here;
1. "harlowe.bridge.js_" line 55
`case "tag":`
`    continue;`
I have just commented out these two lines of codes, (or you could just remove the whole section of code) which ensures that the parser doesn't ignore tags.

2. "HarloweTranscoder.cs" line 163, where text gets processed
`case "text":`
I've added a new case tag for it to handle HTML tags like text
`case "tag": // added HTML tags to be processed like normal text`

So the new case statement looks like this:
`case "text":`
`case "tag": // added HTML tags to be processed like normal text`
`Code.Indent();`
`GenerateText(token.text, true);`
`break;`

And that's it. That was all that was needed to get HTML tags to work with Harlowe.
