### ISSUE TITLE
TwineTextPlayer adding "Word" to the end of each line in imported Harlowe stories

### ISSUE THREAD

**Issue by BuzzardMercure** [daterre/Cradle#33]
This problem doesn't seem to be occuring with SugarCube formatted stories.

Essentially, at each line break of an imported Harlowe format story it adds the "Word" to the end of the line.

This is also happening for me with the 'Clockwork' example provided in the latest commit.

**Comment by BuzzardMercure** [comment]
The LineBreakTemplate child of the Content object had a text field that contained "Word".  I erased it and that solve the issue.

**Comment by daterre** [comment]
Sorry it took me a while to answer, happy you found the source. I'll change it in the project sourcecode.
