### ISSUE TITLE
Errors with Unity 5.5; perhaps due to UTT?

### ISSUE THREAD

**Issue by johnbourne** [daterre/Cradle#35]
Hello:  I’ve been following your work on Cradle and thought I would try it out today.  I have partially working things, but thought I would run by the group about whether I am doing things correctly and how to fix those problems I have run across.   

1.  I figured I needed to down load the most recent commits so I downloaded the Dec. 4 (4aa9c8b) in a zip file, and opened with Unity5.5.  I allow it to upgrade to 5.5.
2. After opening the unity browser I get in the console that Mono.Cecil….. is not found… with UNetWeaver error.
3. I noticed in some posts that people thought that a new UnityTestTools was needed.  I tried downloading from the Asset Store - but that didn’t do anything.  I looked up UTT and found that it isn’t compatible with Unity 5.5.  So, I deleted UTT.
4. Wanting to look at Snoozing, I loaded the scene from the examples directory.
5. I get the message:  StoryImportException: Macro 'assert' does not exist. You can add it as a custom macro, please see the Cradle documentation page and
6. Assets/Cradle/Tests/Stories/HarloweTests/HarloweTests.cs(63,18): error CS0246: The type or namespace name `UnityTwineTestMacros' could not be found. Are you missing an assembly reference?
7. So, I deleted HarloweTests.cs figuring it was using nasty UTT.
8. Then there was on error left: StoryImportException: Macro 'assert' does not exist. You can add it as a custom macro, please see the Cradle documentation page.
9. Following this advice, I looked for adding assert in the documentation. Found nothing.
10. Now the above steps are the second time I tried this - the first time I got it to work by deleting some other scripts that were causing a problem;  but they don’t seem to exist now.  
11. So, need a bit of help to get this percolating, it seems.  I am running on a Mac and want to use SugarCube.
12. Suggestions welcomed.

**Comment by johnbourne** [comment]
Sorry, most of the above was solved when restarting Unity.... who knows.  However, I am wondering about writing macros - seems straightforward from the documentation.  However, the attribute [RealtimeMacro]  is unknown to the Mono.  I looked for attributes in the Unity 5.5 docs, but this was not one of them.  A more complete recommendation about how to do macros would be very helpful.  I am really impressed that I can use twine 2 and it easily generates the c# file (oh, so nice).  However,  adding macros has not worked for me - wonder if there are workarounds?

tnx,

**Comment by Flyingvette** [comment]
I am having the same problems, however restarting Unity has only been temporarily fixing the problem for me, as in it sometimes will compile for a run but often times will not.  The Mono dll seems to be the culprit.

**Comment by daterre** [comment]
Hi,

Sorry it took me a while to get back to you. Thanks for checking out Cradle again! Hope I can I get it running smoothly for you.

Regarding the macro, I think the macro you are talking about is RuntimeMacro (not realtime). Let me know if that solved your problem.

Regarding the Mono Cecil stuff, Unity does seem to move it around from one version to the next. Maybe something is wrong with the path. I haven't done any thorough testing yet with 5.5 so I'll get to that ASAP.

Regarding Unity Test Tools, this really doesn't need to be in the distribution of the plugin. You can remove it along with any of the related Story Format tests.

**Comment by daterre** [comment]
I updated to 5.5.1 and updated UnityTestTools, that seems to have solved those Mono errors.
