### ISSUE TITLE
Runtime Macros passed reference to Story/Passage which calls it

### ISSUE THREAD

**Issue by BrodyB** [daterre/Cradle#36]
It would be a nice addition to have Sugar/Harlowe runtime macros receive a reference to the passage or story that calls it as a first attribute. So for example:

> [Cradle.RuntimeMacro("setRoom")]
> public void SetRoom (StoryPassage passage, string roomName)
> {
> 	// passage is automatically populated with the story passage which called this macro
> }

This would be useful for scenes that use multiple stories where I want a macro do things that affect only the story responsible for executing it.

**Comment by daterre** [comment]
Nice idea, thanks! Sounds like you're putting Cradle to some interesting
use. I hope I get a chance soon to go through a bunch of todo's and get a
new version out with an actual unitypackage.

**Comment by BrodyB** [comment]
I changed SugarCodeGenMacros on my end to implement this. I'll make a pull request this weekend on the main repo. Haven't looked into where to inject the change for Harlow.

**Comment by BrodyB** [comment]
Alright, I'm unable to push a new branch to the repo (no permissions), so here's the fix:

In SugarCodeGenMacros.cs, DisplayShorthand() is slightly modified to include a reference to _this_:
```
public static SugarCodeGenMacro DisplayShorthand = (transcoder, macro, argument) =>
{
	string args = argument != null ? transcoder.BuildExpression(argument) : null;
	if (!string.IsNullOrEmpty(args))
		args = SugarTranscoder.ParamsWithCommas(args);

	transcoder.Code.Indent();

	MacroDef macroDef;
	if (transcoder.Importer.Macros.TryGetValue(macro, out macroDef))
	{
		string arguments = string.IsNullOrEmpty(args) ? "this" : "this, " + args;
		transcoder.Code.Buffer
			.AppendFormat("{0}.{1}({2});", macroDef.Lib.Name, macroDef.Name, arguments)
			.AppendLine();
	}
	else
	{
		string passageExpr = transcoder.BuildExpression(macro);
		
		transcoder.Code.Buffer
			.AppendFormat("yield return passage(\"{0}\"{1});", passageExpr, (!string.IsNullOrEmpty(args) ? ", " : string.Empty) + args)
			.AppendLine();
	}
};
```

For someone currently using Cradle with Sugar and upgrading to the latest version, they'd have to reimport any of their stories and update their runtime macros to include a Cradle.Story argument as the first argument.

Currently using this in my project and it's going well so far!

**Comment by daterre** [comment]
Wouldn't Story.CurrentPassageName allow you to access the current passage which invoked the macro?

**Comment by BrodyB** [comment]
In a case where there are multiple stories present in a scene, no, since the question becomes "which story do I ask?" So, by having a reference to the story that calls the macro, I can reliably know which story in the scene to perform an action for (or find the script that's handling that story).

I'm assuming Cradle was built with the intention of working with one Twine story to drive events in the scene, but I'm finding that with a minor adjustment like this, it's easy to get multiple working at the same time.

**Comment by daterre** [comment]
Runtime macro methods are defined inside a class that inherits from RuntimeMacros, which has a property called Story. If two stories use the same macro library, every story gets its own instance of the library, So simply checking Story and Story.CurrentPassageName should do what you need.

**Comment by BrodyB** [comment]
Ohhh, gotcha, gotcha. I misunderstood the first time. Yes, I tried swapping in the public Story reference into my macros instead of the local reference I slipped in and this does exactly the same thing. I should have dug a little deeper before shoehorning this in.

Thanks!
