### ISSUE TITLE
Win32Exception on Twine Story Import

### ISSUE THREAD

**Issue by domportera** [daterre/Cradle#37]
EDIT: To anyone reading this, errors pertaining to the use of the proper compatible version of Unity start in the 3rd reply to this thread

Error 1:

Assets/Cradle/UnityTestTools/Examples/UnitTestExamples/Editor/SampleTests.cs(74,10): error CS0246: The type or namespace name `ExpectedException' could not be found. Are you missing an assembly reference?

Error 2 (this occurs on Twine HTML import):
Win32Exception: ApplicationName='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/ThirdParty/PhantomJS/bin/win/phantomjs.exe', CommandLine='"phantom.js_" "file:///D:/OneDrive/School/Senior%20Thesis/Project/Development/Unity/Uproot/Assets/Twine/Day11.html" "D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js/StoryFormats/Harlowe/harlowe.bridge.js_"', CurrentDirectory='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Cradle.Editor.Utils.PhantomJS.Run[HarloweStoryData] (System.String url, System.String bridgeScriptPath, Boolean throwExOnError) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/Utils/PhantomJS.cs:37)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.Init () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:113)
Cradle.Editor.StoryImporter.Transcode () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:44)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:29)

Using Unity Beta 5.6.0b11. Any idea on how I can fix this? I can't import any Twine stories. Thanks in advance! I'm really looking forward to working with this plugin.

**Comment by daterre** [comment]
It looks like an incompatibility of Unity's Test Tools with their 5.6 beta.
Cradle doesn't officially support 5.6 yet, you can try to remove the
UnityTestTools folder and the Cradle/Tests folder, that might work.

**Comment by domportera** [comment]
I got all kinds of errors when I did that, so I downgraded to 5.5.2f1, which provided me with a couple more errors listed below. I will downgrade to 5.5.1 since that is your most recent supported version, and I'll let you know.

Error 1:
Win32Exception: ApplicationName='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/ThirdParty/PhantomJS/bin/win/phantomjs.exe', CommandLine='"phantom.js_" "file:///D:/OneDrive/School/Senior%20Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Cradle/Examples/Clockwork/Clockwork.html" "D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js/StoryFormats/Harlowe/harlowe.bridge.js_"', CurrentDirectory='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Cradle.Editor.Utils.PhantomJS.Run[HarloweStoryData] (System.String url, System.String bridgeScriptPath, Boolean throwExOnError) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/Utils/PhantomJS.cs:37)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.Init () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:113)
Cradle.Editor.StoryImporter.Transcode () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:44)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)


Error 2:
Win32Exception: ApplicationName='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/ThirdParty/PhantomJS/bin/win/phantomjs.exe', CommandLine='"phantom.js_" "file:///D:/OneDrive/School/Senior%20Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Cradle/Tests/Stories/SugarTests/SugarTests.html" "D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js/StoryFormats/Sugar/sugar.bridge.js_"', CurrentDirectory='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Cradle.Editor.Utils.PhantomJS.Run[SugarStoryData] (System.String url, System.String bridgeScriptPath, Boolean throwExOnError) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/Utils/PhantomJS.cs:37)
Cradle.Editor.StoryFormats.Sugar.SugarTranscoder.Init () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Sugar/SugarTranscoder.cs:191)
Cradle.Editor.StoryImporter.Transcode () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:44)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)

**Comment by domportera** [comment]
Ok, I have downgraded to 5.5.1f1 (sorry for the extra step!) and still have an error when trying to import a Twine story, taken straight from vanilla Twine 2.1.1 using their online editor

Here's the error:

Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/ThirdParty/PhantomJS/bin/win/phantomjs.exe', CommandLine='"phantom.js_" "file:///D:/OneDrive/School/Senior%20Thesis/Project/Development/Unity/Uproot/Assets/Twine/Day12.html" "D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js/StoryFormats/Harlowe/harlowe.bridge.js_"', CurrentDirectory='D:/OneDrive/School/Senior Thesis/Project/Development/Unity/Uproot/Assets/Cradle/Editor/js'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
Cradle.Editor.Utils.PhantomJS.Run[HarloweStoryData] (System.String url, System.String bridgeScriptPath, Boolean throwExOnError) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/Utils/PhantomJS.cs:37)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.Init () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:113)
Cradle.Editor.StoryImporter.Transcode () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:44)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)

**Comment by domportera** [comment]
I re-installed Cradle, figuring I just installed it incorrectly, and that was the case. Sorry for the trouble! please disregard this and feel free to delete the issue.

**Comment by daterre** [comment]
Glad it worked! It's quite sensitive to the install location at the moment,
I need to figure out a way to improve that.

**Comment by domportera** [comment]
I don't think that's too big of an issue. Just as someone who has never installed a Unity plugin manually, I didn't realize that I was dropping the files a folder too deep (inside the asset folder itself, including the Project Settings), rather than the project directory. If you'd like, I can whip up a quick gif on the proper installation of the plugin for noobs like me
