### ISSUE TITLE
NullReferenceException - Hardcoded Path?

### ISSUE THREAD

**Issue by Mourkain** [daterre/Cradle#42]
Just downloaded the latest Snapshot and opened it with Unity 5.6.1.
I'm getting the Following Error with your example Scenes.

NullReferenceException: Object reference not set to an instance of an object
Cradle.Story.get_CurrentPassageName () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle/Core/Story.cs:68)
StoryInspector.OnInspectorGUI () (at D:/Projects/UnityTwine/git/Assets/Cradle/.src/Cradle.Editor/Editor/StoryInspector.cs:22)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1229)
UnityEditor.DockArea:OnGUI()

**Comment by daterre** [comment]
Thanks @Mourkain, I fixed it. It was a small problem with the story inspector.
