### ISSUE TITLE
Compilation errors in editor scripts when using platforms that don't support System.IO (e.g. WebPlayer)

### ISSUE THREAD

**Issue by Blueduckraider50** [daterre/Cradle#5]
Assets/Plugins/UnityTwine/Editor/TweeAssetProcessor.cs(32,80): error CS0117: `System.IO.File' does not contain a definition for `ReadAllText'

How to fix?
Any idea?

**Comment by daterre** [comment]
What platform are you on?

**Comment by Blueduckraider50** [comment]
Web Player. (Woah, fast response :O )

**Comment by daterre** [comment]
Email notifications yay :) I think I see the problem. System.IO is not supported on the Web Player, but this is the editor! For some reason Unity is not treating the UnityTwine editor scripts as, well, editor scripts. Try moving the Editor folder from Assets/Plugins/UnityTwine to Assets. That should solve it. (I'll try to fix this for the next release)

**Comment by Blueduckraider50** [comment]
That seems to have removed the error, thanks! :D

**Comment by daterre** [comment]
This has been rectified in the new version of Cradle by moving the plugin code into dedicated DLLs.
