### ISSUE TITLE
Add event Story.OnVariableChanged

### ISSUE THREAD

**Issue by daterre** [daterre/Cradle#50]
Possible handler signature:
`Story.OnVariableChanged(Story story, string varName, StoryVar newValue, StoryVar previousValue)`

See #49 for use-case.

**Comment by BrodyB** [comment]
I've implemented essentially the same thing on my local version (though I can't make pull requests).

In Story, I declared an OnVariableSet event:
```
public event Action<string, StoryVar> OnVariableSet;
```

Then at the bottom of RuntimeVars.SetMember():
```
// Invoke the Story OnVariableSet event
Story.OnVariableSet.Invoke(varName, newVar);
```

After that, any Unity script can just subscribe with `story.OnVariableSet += OnVariableSet`.

**Comment by daterre** [comment]
That looks pretty good. Why can't you make pull requests? The repo is set up to accept them from anyone. Do you have a fork?

**Comment by BrodyB** [comment]
I don't have a fork. I remember a few months ago attempting to even create a branch and having that be denied! I figured you had stricter permissions on the repo. I can attempt to pull down tonight (I'm on UTC-8:00, California) and make changes and see if it's any different.

**Comment by BrodyB** [comment]
I've spent the last couple of hours trying to troubleshoot why I'm unable to push branches up to this repo, but I keep getting the same answer:
```
remote: Permission to daterre/Cradle.git denied to BrodyB.
```
I haven't had this issue with other repos on GitHub or elsewhere, so maybe there's some privacy setting switched in this repo? Otherwise, I could just list my changes here (which is obviously less ideal).

**Comment by daterre** [comment]
You are right that I didn't open the repo to direct pull requests, but if
you fork the repo to your account I believe you should be able to make a
pull request as detailed here
<https://help.github.com/articles/creating-a-pull-request-from-a-fork/>.

Regarding the event handler signature, since the value returned has no
reference to the story object it would probably be a good idea to add it.
That way multiple stories could register the same handler and still know
which story initiated the var set.

**Comment by BrodyB** [comment]
Ah, gotcha! I misunderstood.

I made the changes and created a pull request from my own fork.

**Comment by BrodyB** [comment]
Sorry about the silence on this issue. I've just been returning to it on my project, and I've realized a challenge in implementing this feature as an event on a story that's invoked by RuntimeVars.SetMember().

In generated Story scripts (at least when using Sugar), when getting or setting StoryVars, they're directly accessed (i.e. ```Vars.variableName = 2;```). This means that SetMember() is never called and there's no easy point to insert a catch-all command. Not sure I know a way to slip this in without changing the story generation code.

Thoughts?

**Comment by daterre** [comment]
Hmm, good point. I haven't had a chance yet to test the pull request but this does seem like a loophole. The reason the story variables are class fields and not properties (which could have allowed inserting a catch-all in the setter) is that StoryVar is a struct, and C# does not allow directly changing structs' sub-fields via script unless they are exposed directly (as opposed to being returned by a getter, which actually clones the value). 

With that explanation out of the way, it seems to me that the best bet for your original use case would be to create a new story var synchronizer class that would go over each assigned story in its Update loop and compare all variables to detect changes. Here is an (untested) script that does just that - let me know if it works for you.

```c#
using System.Collections.Generic;
using UnityEngine;
using StoryVarSet = System.Collections.Generic.Dictionary<string, Cradle.StoryVar>;

namespace Cradle.Utilities
{
	public class StoryVarSynchronizer: MonoBehaviour
	{
		[Tooltip("The stories to synchronize. The first story gets the highest priority in case of a conflict.")]
		public Story[] Stories;

		Dictionary<Story, StoryVarSet> _previousValues = new Dictionary<Story, StoryVarSet>();
		StoryVarSet _changes = new StoryVarSet();

		void Update()
		{
			// Clean all previous recorded changes
			_changes.Clear();

			// Go over every story and check for changed variables
			for (int i = 0; i < Stories.Length; i++)
			{
				Story story = Stories[i];
				StoryVarSet previousValues;

				// If no previous values were stored for this story, create a new set to store them in
				if (!_previousValues.TryGetValue(story, out previousValues))
					_previousValues.Add(story, previousValues = new StoryVarSet());

				// Go over every variable and compare with its previous value
				foreach (var variable in story.Vars)
				{
					// Get current and previous values for this story
					StoryVar currentValue = variable.Value;
					StoryVar previousValue = default(StoryVar);

					// Compare to previous
					if (previousValues.TryGetValue(variable.Key, out previousValue))
					{
						// A change has been detected in this variable, and no other story has changed it in this frame
						if (previousValue != currentValue && !_changes.ContainsKey(variable.Key))
							_changes.Add(variable.Key, currentValue);
					}

					// Keep track of the previous value
					previousValues[variable.Key] = currentValue;
				}
			}

			// Go over every story again, this time applying the changed variables
			for (int i = 0; i < Stories.Length; i++)
			{
				Story story = Stories[i];
				foreach (var variable in _changes)
				{
					if (story.Vars.ContainsKey(variable.Key))
						story.Vars[variable.Key] = variable.Value;
				}
			}
		}
	}
}
```

**Comment by daterre** [comment]
This script has been added to Utils so I'm closing the issue.
