### ISSUE TITLE
Namespace "HtmlTag" cannot be found - Mac / MonoDevelop

### ISSUE THREAD

**Issue by BrodyB** [daterre/Cradle#52]
When attempting to build the DLL on macOS using MonoDevelop 5.9.6, I receive the error: `The type or namespace 'HtmlTag' could not be found. Are you missing an assembly reference?` relating to method `Story.htmlTag(StoryVar text)`.

This isn't seen on commit 4aa9c8b (Dec 4th, 2016), which is the version I've been working with thus far.

**Comment by daterre** [comment]
Fixed!
