### ISSUE TITLE
"Text player does not have a story to play" story class error

### ISSUE THREAD

**Issue by eccentricpineapple** [daterre/Cradle#54]
I'm fairly new to Unity and in all likelihood this is a pretty simple fix - I appreciate any help you can give.

I was able to import my Twine file, create the C# script and attach it to the TwineTextPlayer prefab. However I'm now getting the following error: "Text player does not have a story to play. Add a story script to the text player game object, or assign the Story variable of the text player. UnityEngine.Debug:LogError(Object)"

A similar error was previously discussed [here](https://github.com/daterre/Cradle/issues/12), though I'm not sure the answers given apply to the current version of Cradle. I can tell the error has something to do with the way I used the story class and defined the StartPassage. Unfortunately the more I try to fix it the more I break the script. Any advice?

**Comment by daterre** [comment]
Hi, could you attach a screenshot of the inspector showing your TwineTextPlayer component? That might give me some clues.
