### ISSUE TITLE
NullReferenceException on import of story

### ISSUE THREAD

**Issue by phoebeanh** [daterre/Cradle#59]
Hi! I tried importing my Twine story only to get a null ref exception. I'm not sure where the issue is happening at? I'm using Harlowe, Twine 2.2.1, and Unity 2017.1.1f1

here is the error code:
`NullReferenceException: Object reference not set to an instance of an object
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.GenerateExpression (Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, Int32 start, Int32 end) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:391)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.BuildExpressionSegment (Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, System.Int32& tokenIndex) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:442)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.GenerateExpression (Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, Int32 start, Int32 end) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:397)
Cradle.Editor.StoryFormats.Harlowe.BuiltInCodeGenMacros+<>c.<.cctor>b__14_1 (Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder transcoder, Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, Int32 tokenIndex, MacroUsage usage) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweCodeGenMacros.cs:75)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.GenerateMacro (Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, Int32 macroTokenIndex, MacroUsage usage) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:335)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.GenerateBody (Cradle.Editor.StoryFormats.Harlowe.LexerToken[] tokens, Boolean breaks) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:236)
Cradle.Editor.StoryFormats.Harlowe.HarloweTranscoder.PassageToCode (Cradle.Editor.PassageData p) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryFormats/Harlowe/HarloweTranscoder.cs:145)
Cradle.Editor.StoryImporter.Transcode () (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:54)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:83)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)`

**Comment by daterre** [comment]
Hi @phoebeanh, any chance you could provide me a version of your story that this happens with? It might be due to a new version of Twine that is not yet fully supported by Cradle, but I'd have to check.

**Comment by daterre** [comment]
Closed due to no response...
