### ISSUE TITLE
Adding to or changing "additional hooks" during the game doesn't update _hookTargets

### ISSUE THREAD

**Issue by jamesShasha** [daterre/Cradle#6]

**Comment by daterre** [comment]
Try calling TwineStory.HooksClear(). This clears the hook cache so that the next time a passage is hit, it scans the AdditionalHooks list again. A bit hacky, I know, I'll make it more transparent in the next version.

**Comment by jamesShasha** [comment]
I couldn't find a function called HooksClear() ?

**Comment by daterre** [comment]
Oops it was added after the 1.1 release, sorry about that. It will be available in the next release. In the meantime you can copy it temporarily from the latest version of the file: https://github.com/daterre/UnityTwine/blob/master/Core/TwineStory.cs

**Comment by daterre** [comment]
This feature was renamed to CuesClear and is available in Cradle 2.
