### ISSUE TITLE
Can't Import TwineTextPlayer.prefab :(

### ISSUE THREAD

**Issue by Cytronix777** [daterre/Cradle#67]
I imported everything else fine but it keeps crashing/failing to import that prefab:

A default asset was created for 'Assets/Cradle/TwineTextPlayer/TwineTextPlayer.prefab' because the asset importer crashed on it last time.
You can select the asset and use the 'Assets -> Reimport' menu command to try importing it again, or you can replace the asset and it will auto import again.

I've tried using 'import package' and I've tried manually putting it into the folder from the source files but it's not having any of it. Any ideas?

**Comment by daterre** [comment]
Hi, sorry it took a while to get back to you. I've never seen that error and I'm not really sure what could cause it. What Unity version are you running?
Also, before you import Cradle, is your project free of errors?

**Comment by daterre** [comment]
Closing this because I can't recreate it...
