### ISSUE TITLE
How to determine if a passage has been seen?

### ISSUE THREAD

**Issue by fragmental** [daterre/Cradle#71]
What is the best way to determine if a passage has been seen?  I know that I can use state tracking + conditional logic in the twine itself to add and check variables, but that doesn't work well for my needs.   I want to be able to check every single passage, even the first one, and it would be better if no additional measures were necessary when creating the twine itself.

I know that usually people use something like this to determine if a choice should be shown or hidden, but that's not my intent.  Basically, what I want to do is subtract 1 from an int if the passage has not been seen, but do nothing if it has been seen.

**Comment by daterre** [comment]
You can check Story.PassageHistory.Contains("passage name"), it's a list containing a chronological list of visited passages (newest to oldest)
