### ISSUE TITLE
Stories not generating C# scripts

### ISSUE THREAD

**Issue by gaialabsoc** [daterre/Cradle#72]
when i am importing html file its not generating c# script . I am using twine 2 and saving html in assets folder

**Comment by HannahLovberg** [comment]
I had the same problem and solved it by renaming the file. It seems sensitive to naming syntax so make sure to only use letters and numbers in the name.

**Comment by justinliew** [comment]
When I try to import I'm seeing this. Not sure if it's related. I'm trying to look into it.

`NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.get_Location () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Cradle.Editor.StoryImporter+<LoadMacrosInto>d__30.MoveNext () (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:78)
System.Collections.Generic.HashSet`1[T].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
Cradle.Editor.StoryImporter.Transcode () (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:42)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:83)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:141)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by justinliew** [comment]
I figured out the isssue above. If you switch to >= .NET 4.0 and then add assembly.IsDynamic checks around all the calls to Location, it fixes it. If you want a PR let me know. Otherwise I'll just use this local copy for my own purposes.

**Comment by daterre** [comment]
Please do! Sorry for taking a while to respond, I haven't had any time recently to maintain the peoject. PR will be very helpful indeed.

**Comment by wordsonplay** [comment]
I'm having the same issue. A fix would bw great.

**Comment by justinliew** [comment]
I will try to get to this hopefully this week. I made the changes back in December when using this lib for a game jam so just have to resurrect and verify them, and make a proper PR.

**Comment by ebertozz** [comment]
Was this fixed? I am having the same issue. Thanks
