### ISSUE TITLE
Jump on a specific passage

### ISSUE THREAD

**Issue by gr3tchel** [daterre/Cradle#73]
My Start passage is not linked with "Passage 1", but "Passage 1" is linked to Start.
Now, all I want to do is to Jump on "Passage 1" by doing a specific action out of Cradle. For example, the player press the Spacebar and it is supposed to jump on "Passage 1".
I tried to uso GoTo but I get this error 
"NullReferenceException: Object reference not set to an instance of an object
Cradle.Story.GetLink (System.String linkName, Boolean throwException) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle/Core/Story.cs:632)
Cradle.Story.DoLink (System.String linkName) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle/Core/Story.cs:616)"

Is it a proper use of GoTo?
Thanks

**Comment by daterre** [comment]
You can use GoTo (even though I recommend against it) but judging by your stack trace it looks like you used DoLink with a passage name - that won't work
