### ISSUE TITLE
NotSupportedException on Windows C#6 version

### ISSUE THREAD

**Issue by DarkRewar** [daterre/Cradle#74]
Hello, I'm using the last version of Cradle on Unity 2018.2.14f1 with the .NET 4.X equivalent (C#6) and when I import a Twinery (Harlow 2.1 or 1.2.4), I've got an NotSupportedException error like this : 

NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.get_Location () (at <f2e6809acb14476a81f399aeb800f8f2>:0)
Cradle.Editor.StoryImporter+<LoadMacrosInto>d__34.MoveNext () (at D:/Projects/blind drive/git/Blind Drive/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:80)
System.Collections.Generic.HashSet`1[T].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <839a3cb835c04d14aeb58d83bb7bc4bd>:0)
Cradle.Editor.StoryImporter.Transcode () (at D:/Projects/blind drive/git/Blind Drive/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:44)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at D:/Projects/blind drive/git/Blind Drive/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:85)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:140)

When I move to C#4 (.NET 3.X Equivalent), I have no problem, but I must code my project on the .NET 4.X framework. Is there something to do or Cradle cannot be used on .NET 4 ?

**Comment by wordsonplay** [comment]
A bit of googling suggests that the problem is when StoryImporter references Assembly.Location on a dynamic assembly. This is not supported in .NET 4 and later. 

https://social.msdn.microsoft.com/Forums/vstudio/en-US/94c0fe05-5a83-40f6-b321-5fa30e7156b9/dynamic-assemblies-and-assemblylocation-limitations?forum=netfxbcl

Suggested fix. Add this code before StoryImporter.cs:80

```
// Skip dynamic assemblies
if (assembly.IsDynamic) continue;

```

**Comment by DarkRewar** [comment]
Thank you for your help 👍 but, same error appears in the Reflection Assembly Builder...

```
NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.get_Location () (at <f2e6809acb14476a81f399aeb800f8f2>:0)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at <18ff42ebf1cb42eea6f6021b84a5bea9>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:140)
```

**Comment by justinliew** [comment]
This is the same as https://github.com/daterre/Cradle/issues/72 I believe. I have a fix but don't know if the maintainer is still active. I'll submit a PR but if that doesn't work we can figure out how to fix this up so people can continue to use it.

**Comment by DarkRewar** [comment]
Okay, so what's I've done : I wrote `!assembly.IsDynamic` in the CradleAssetProcessor.cs:158 and regenerate the project. Thanks Justin !

```csharp
foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
    if (!assembly.IsDynamic && !string.IsNullOrEmpty(assembly.Location))
        compilerSettings.ReferencedAssemblies.Add(assembly.Location);
```

**Comment by daterre** [comment]
Since Cradle aims to be backward compatible with .NET 3.5, I fixed this with a try catch instead.

**Comment by mifozski** [comment]
For anyone who's still having a problem with the story importing even when using the released package from Github and don't want to go through all the process (cloning, fixing in, building, packaging) to fix it themselves, I basically did all this and released it at https://github.com/mifozski/Cradle/releases/tag/v2.0.1-importfix.
Note: this release is built from the top of the tree and is incompatible with stories generated with official v.2.0.1 because there were some changes made after that.
Also, it's built upon .NET 4.5 and is indented to be used with Unity set to use .NET 4.* Equivalent runtime.
