### ISSUE TITLE
Can't generate .cs file

### ISSUE THREAD

**Issue by valkyriq** [daterre/Cradle#76]
When I tried to import Twine story into unity and I have a problem with generate .cs file from html 
I get en error:
NotSupportedException: The invoked member is not supported in a dynamic module.
System.Reflection.Emit.AssemblyBuilder.get_Location () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Cradle.Editor.StoryImporter+<LoadMacrosInto>d__30.MoveNext () (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:78)
System.Collections.Generic.HashSet`1[T].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
Cradle.Editor.StoryImporter.Transcode () (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/StoryImporter.cs:42)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/Projects/(external)/Cradle/unity/Cradle/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:83)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:141)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

PS: I'm using mac

**Comment by daterre** [comment]
Hi, this was fixed in #74, if you're using the asset store version it hasn't yet been updated. I recommend cloning the repository straight into your project.
