### ISSUE TITLE
Sugarcube Code: <<timed "2s">> <<goto "passage">> throwing error logs

### ISSUE THREAD

**Issue by taulant** [daterre/Cradle#86]
**What I did:**
Wanted to create a passage that moves automatically after a certain time frame. I am using Sugarcube's `<<timed>>` & `<<goto>>` functions

**What I was expecting:**
The passage to move automatically after the time specified in the `<<timed>>` 
Example: `<<timed "5s">>`

**What happened:**
Cradle threw an error in the Unity console log mentioning that "timed" is not recognized.

`StoryException: Passage 'timed' does not exist.`

Wondering if there is a workaround to this?

**Comment by daterre** [comment]
As a rule, time-related macros are not implemented in Cradle because it is considered a presentation feature, and Cradle treats Twine stories as pure narrative. (Ideally, the error message would say that). The Cradle way to do the above would be to add a passage cue with a wait:

```c#

[StoryCue("Some passage", CueType.Enter)]
IEnumerator MyPassage_Enter()
{
    var story = GetComponent<Story>();
    story.Pause();
    yield return new WaitForSeconds(5f);
    story.Resume();
}
```

Hope that helps

**Comment by daterre** [comment]
Another fancier way to go about that would be to extend Cradle with your own version of the "timed" macro and add a story output handler that pauses and resumes after a delay whenever that macro is encountered. I'd recommend against that unless you really must maintain full compatibility with an HTML version of your story.

**Comment by taulant** [comment]
@daterre Thanks so much for your notes. Will definitely try your suggestions.

**Comment by taulant** [comment]
@daterre Please mark this as resolved. Your notes were helpful.
