### ISSUE TITLE
Variables give errors

### ISSUE THREAD

**Issue by Seminko** [daterre/Cradle#9]
I have redone my whole story with SugarCube since the default (set: $thing to 1)[blabla] didn't work with UnityTwine. But now I get errors for all < < i f > > statements and all < < set $variable to 2 > >. Is there any way to get around that?

EDIT: Ok, so instead of $variable to 2 you have to to do set $variable = 2

**Comment by daterre** [comment]
Hi, I apologize for the delayed response. I'm glad you figured it out, a new version will be released soon that fixes some syntax potholes in the current version. Unfortunately at the moment I don't have plans to support Harlowe, it would need a rewrite of the import engine.

**Comment by daterre** [comment]
The Harlowe story format is now supported in Cradle (UnityTwine v2).

The 'to' assignment operator is now available in the Sugar story format.
